---
version: 2
jobs:
  update: &update
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v2-npm-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v2-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: .circleci/greenkeeper
      - run:
          name: Updating schema
          command: |
            export GH_TOKEN=$(./scripts/github_token.js 290530)
            git clone "https://x-access-token:$GH_TOKEN@github.com/heroku/typescript-api-schema.git" repo
            cd repo
            yarn
            git config --global push.default simple
            git config --global user.name "$GIT_AUTHOR_NAME"
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            curl https://api.heroku.com/schema -H "Accept: application/vnd.heroku+json; version=3" > schema.json
            cat schema.json | ./node_modules/.bin/json2ts --no-style.semi --style.singleQuote > lib/index.d.ts
            ./node_modules/.bin/tslint --fix lib/index.d.ts
            sed -i -r "s/Heroku(Platform|Build|Setup|Vault)Api([^ ])/\2/" lib/index.d.ts
            git add schema.json lib/index.d.ts
            git commit -m "fix: updated schema" || exit 0
            git push -q origin master
  release:
    <<: *update
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: Install dependencies
          command: |
            yarn global add semantic-release@15
            yarn --frozen-lockfile
      - run:
          name: Cutting release
          command: |
            export PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH
            export GH_TOKEN=$(./scripts/github_token.js 290530)
            git remote set-url origin "https://x-access-token:$GH_TOKEN@github.com/heroku/typescript-api-schema.git"
            semantic-release
      - save_cache:
          key: v2-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  "@heroku-cli/typescript-api-schema":
    jobs:
      - update:
          context: org-global
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - update
  nightly:
    triggers:
      - schedule:
          cron: "0 11 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update:
          context: org-global
